sonar.projectKey=liauli_MBC
sonar.organization=liauli

sonar.sources=MBC/
sonar.inclusions=**/*.swift
sonar.exclusions=Gemfile.lock,vendor/**
sonar.coverageReportPaths=coverage/sonarqube-generic-coverage.xml
sonar.coverage.exclusions=\
  MBCTests/**,\
  MBCDesignSystem/Tests/**,\
  MBC/Resources/**,\
  MBC/App/MBCApp.swift,\
  MBC/App/**Provider.swift,\
  MBC/Data/NFC/NFCService.swift,\
  MBC/Data/PIN/KeychainWrapper.swift,\
  MBC/Presentation/**/*View.swift,\
  MBC/Presentation/Shared/**
